# Generated by Django 6.1 on 2026-09-01 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('desenvolvedora', models.CharField(max_length=100)),
                ('distribuidora', models.CharField(max_length=100)),
                ('plataforma', models.CharField(max_length=100)),
                ('descricao', models.TextField(max_length=500)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8)),
                ('data_lancamento', models.DateField()),
                ('classificacao', models.CharField(max_length=50)),
                ('multiplayer', models.BooleanField(default=False)),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jogos', to='jogos.genero')),
            ],
        ),
    ]
