# Generated by Django 6.1 on 2026-09-02 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogo',
            name='capa',
            field=models.ImageField(blank=True, null=True, upload_to='capas/'),
        ),
    ]
