# Generated by Django 5.2.17 on 2026-09-30 13:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils.text import slugify


def preencher_slug_genero(apps, schema_editor):
    Genero = apps.get_model("jogos", "Genero")
    for genero in Genero.objects.all():
        base = slugify(genero.nome) or f"genero-{genero.pk}"
        slug = base
        n = 1
        while (
            Genero.objects.filter(slug=slug).exclude(pk=genero.pk).exists()
        ):
            slug = f"{base}-{n}"
            n += 1
        genero.slug = slug
        genero.save(update_fields=["slug"])


class Migration(migrations.Migration):

    dependencies = [
        ('jogos', '0002_jogo_capa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plataforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('icone', models.CharField(blank=True, help_text='Classe ou rótulo curto do ícone', max_length=80)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Plataforma',
                'verbose_name_plural': 'Plataformas',
                'ordering': ['nome'],
            },
        ),
        migrations.AlterModelOptions(
            name='genero',
            options={'ordering': ['nome'], 'verbose_name': 'Gênero', 'verbose_name_plural': 'Gêneros'},
        ),
        migrations.AlterModelOptions(
            name='jogo',
            options={'ordering': ['-criado_em', '-id'], 'verbose_name': 'Jogo', 'verbose_name_plural': 'Jogos'},
        ),
        migrations.AddField(
            model_name='genero',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, null=True),
        ),
        migrations.RunPython(preencher_slug_genero, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='genero',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, unique=True),
        ),
        migrations.AddField(
            model_name='jogo',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='jogo',
            name='avaliacao_pessoal',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='jogo',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='banners/'),
        ),
        migrations.AddField(
            model_name='jogo',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='jogo',
            name='generos',
            field=models.ManyToManyField(blank=True, related_name='jogos_extra', to='jogos.genero'),
        ),
        migrations.AddField(
            model_name='jogo',
            name='horas_jogadas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='jogo',
            name='percentual_conclusao',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='jogo',
            name='preco_compra',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='jogo',
            name='slug',
            field=models.SlugField(blank=True, max_length=220),
        ),
        migrations.AddField(
            model_name='jogo',
            name='status',
            field=models.CharField(choices=[('wishlist', 'Lista de desejos'), ('backlog', 'Backlog'), ('playing', 'Jogando'), ('paused', 'Pausado'), ('completed', 'Concluído'), ('mastered', 'Masterizado'), ('dropped', 'Abandonado')], default='backlog', max_length=20),
        ),
        migrations.AddField(
            model_name='jogo',
            name='tags',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='jogo',
            name='ultimo_jogado',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jogo',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jogos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jogo',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='descricao',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='desenvolvedora',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='distribuidora',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='genero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jogos', to='jogos.genero'),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='nome',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='Conquista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.CharField(blank=True, max_length=400)),
                ('icone', models.CharField(blank=True, default='trophy', max_length=80)),
                ('concluida', models.BooleanField(default=False)),
                ('concluida_em', models.DateTimeField(blank=True, null=True)),
                ('jogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conquistas', to='jogos.jogo')),
            ],
            options={
                'ordering': ['concluida', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('game_completed', 'Jogo concluído'), ('wishlist', 'Lista de desejos'), ('achievement', 'Conquista'), ('review', 'Avaliação'), ('general', 'Geral')], default='general', max_length=30)),
                ('titulo', models.CharField(max_length=200)),
                ('mensagem', models.TextField(blank=True)),
                ('lida', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddField(
            model_name='jogo',
            name='plataforma_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jogos', to='jogos.plataforma'),
        ),
        migrations.CreateModel(
            name='SessaoJogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iniciado_em', models.DateTimeField()),
                ('terminado_em', models.DateTimeField(blank=True, null=True)),
                ('duracao_minutos', models.PositiveIntegerField(default=0)),
                ('notas', models.TextField(blank=True)),
                ('jogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessoes', to='jogos.jogo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessoes_jogo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-iniciado_em'],
            },
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comentario', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('jogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='jogos.jogo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-atualizado_em'],
                'unique_together': {('usuario', 'jogo')},
            },
        ),
        migrations.CreateModel(
            name='ItemListaDesejo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prioridade', models.CharField(choices=[('low', 'Baixa'), ('medium', 'Média'), ('high', 'Alta')], default='medium', max_length=10)),
                ('preco_alvo', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('preco_atual', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('notas', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('jogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_lista_desejo', to='jogos.jogo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lista_desejos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-prioridade', '-criado_em'],
                'unique_together': {('usuario', 'jogo')},
            },
        ),
    ]
