# Generated by Django 5.2.17 on 2026-09-30 20:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogos', '0004_popular_dados_v2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avaliacao',
            options={'ordering': ['-atualizado_em'], 'verbose_name': 'Avaliação', 'verbose_name_plural': 'Avaliações'},
        ),
        migrations.AddField(
            model_name='plataforma',
            name='descricao',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='plataforma',
            name='fabricante',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='comentario',
            field=models.TextField(blank=True, verbose_name='Comentário'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de criação'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='jogo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='jogos.jogo', verbose_name='Jogo'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='nota',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Nota'),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='genero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jogos', to='jogos.genero', verbose_name='Gênero'),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='plataforma_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jogos', to='jogos.plataforma', verbose_name='Plataforma'),
        ),
    ]
