# Generated by Django 5.2.17 on 2026-09-30 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogos', '0005_alter_avaliacao_options_plataforma_descricao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genero',
            name='descricao',
            field=models.TextField(blank=True, max_length=300, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='genero',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='plataforma',
            name='descricao',
            field=models.TextField(blank=True, max_length=300, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='plataforma',
            name='fabricante',
            field=models.CharField(blank=True, max_length=120, verbose_name='Fabricante'),
        ),
        migrations.AlterField(
            model_name='plataforma',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
    ]
