# Generated by Django 5.2.17 on 2026-09-30 20:16

from django.db import migrations, models
from django.utils.text import slugify


def separar_plataformas(apps, schema_editor):
    Jogo = apps.get_model("jogos", "Jogo")
    Plataforma = apps.get_model("jogos", "Plataforma")

    for jogo in Jogo.objects.select_related("plataforma_ref"):
        nomes = jogo.plataforma or ""
        if not nomes and jogo.plataforma_ref_id:
            nomes = jogo.plataforma_ref.nome

        for nome in nomes.split(","):
            nome = nome.strip()
            if not nome:
                continue
            if nome in {"Xbox Series X|S", "Xbox Series X/S"}:
                nome = "Xbox Series X/S"

            slug = slugify(nome) or "outra"
            plataforma = Plataforma.objects.filter(slug=slug).first()
            if plataforma is None:
                plataforma = Plataforma.objects.create(nome=nome, slug=slug)
            elif plataforma.nome != nome:
                plataforma.nome = nome
                plataforma.save(update_fields=["nome"])
            jogo.plataformas.add(plataforma)


def remover_plataformas_combinadas(apps, schema_editor):
    Plataforma = apps.get_model("jogos", "Plataforma")
    Plataforma.objects.filter(nome__contains=",").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('jogos', '0006_alter_genero_descricao_alter_genero_nome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogo',
            name='plataformas',
            field=models.ManyToManyField(blank=True, related_name='jogos', to='jogos.plataforma', verbose_name='Plataformas'),
        ),
        migrations.RunPython(separar_plataformas, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='jogo',
            name='plataforma',
        ),
        migrations.RemoveField(
            model_name='jogo',
            name='plataforma_ref',
        ),
        migrations.RunPython(remover_plataformas_combinadas, migrations.RunPython.noop),
    ]
