# Generated by Django 5.2.17 on 2026-09-30 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogos', '0007_remove_jogo_plataforma_remove_jogo_plataforma_ref_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogo',
            name='fonte_dados',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='jogo',
            name='fonte_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='jogo',
            name='id_externo',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
