# Generated by Django 5.2.17 on 2026-09-30 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jogos', '0008_jogo_fonte_dados_jogo_fonte_url_jogo_id_externo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jogo',
            name='fonte_dados',
        ),
        migrations.RemoveField(
            model_name='jogo',
            name='fonte_url',
        ),
        migrations.RemoveField(
            model_name='jogo',
            name='id_externo',
        ),
    ]
